site_name: Справочник SolidJS
site_url: https://soliddev.ru/
site_description: Справочник SolidJS разработчика
site_author: soliddev.ru
copyright: (C) 2023, Справочник SolidJS разработчика

repo_name: 'Справочник на Github'
repo_url: 'https://github.com/xsltdev/soliddev.ru'

theme:
    name: material
    custom_dir: overrides
    palette:
        - media: '(prefers-color-scheme: light)'
          scheme: default
          primary: light blue
          accent: light blue
          toggle:
              icon: material/toggle-switch-off-outline
              name: Тёмная тема
        - media: '(prefers-color-scheme: dark)'
          scheme: slate
          primary: light blue
          accent: light blue
          toggle:
              icon: material/toggle-switch
              name: Светлая тема
    language: ru
    features:
        - navigation.prune
        - navigation.tabs
        - navigation.tracking
        - navigation.top
        - navigation.footer
        - navigation.indexes
        - content.action.edit
        - content.code.copy
    favicon: solidjs.svg
    logo: solidjs.svg

extra:
    generator: false
    social:
        - icon: fontawesome/brands/html5
          link: 'https://hcdev.ru/'
          name: HTML and CSS docs
        - icon: fontawesome/brands/js
          link: 'https://scriptdev.ru/'
          name: Javascript
        - icon: fontawesome/brands/angular
          link: 'https://angdev.ru/'
          name: Angular docs
        - icon: fontawesome/brands/react
          link: 'https://reactdev.ru/'
          name: React docs
        - icon: fontawesome/brands/solid
          link: 'https://soliddev.ru/'
          name: SolidJS docs
        - icon: fontawesome/solid/mobile-screen
          link: 'https://reactnativedev.ru/'
          name: React Native docs
        - icon: fontawesome/brands/node-js
          link: 'https://nodejsdev.ru/'
          name: Node.js docs
        - icon: fontawesome/brands/python
          link: 'https://py3dev.ru/'
          name: Python 3 docs
        - icon: fontawesome/solid/code
          link: 'https://xsltdev.ru/'
          name: XSLT docs
        - icon: fontawesome/solid/database
          link: 'https://dbasedev.ru/'
          name: Базы данных

markdown_extensions:
    - admonition
    - toc:
          permalink: true
    - pymdownx.extra
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde
    - pymdownx.details
    - pymdownx.emoji:
          emoji_index: !!python/name:materialx.emoji.twemoji
          emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.tabbed:
          alternate_style: true
    - pymdownx.highlight:
          pygments_lang_class: true
          linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - pymdownx.arithmatex:
          generic: true
    - pymdownx.smartsymbols

plugins:
    - search:
          lang:
              - ru
              - en
    - awesome-pages
    - social

extra_css:
    - '/assets/stylesheets/styles.css?1'
